"""empty message

Revision ID: 3018bd94b3cc
Revises: 37b86e0c6819
Create Date: 2022-04-15 22:17:08.528931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3018bd94b3cc'
down_revision = '37b86e0c6819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deals_dealer_id_fkey', 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'dealers', ['dealer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key('deals_dealer_id_fkey', 'deals', 'dealers', ['dealer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
