"""empty message

Revision ID: 3ed7dd81fb12
Revises: 277681a20329
Create Date: 2022-04-15 22:21:42.892909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed7dd81fb12'
down_revision = '277681a20329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deals_dealer_id_fkey', 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'dealers', ['dealer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key('deals_dealer_id_fkey', 'deals', 'dealers', ['dealer_id'], ['id'])
    # ### end Alembic commands ###
