"""empty message

Revision ID: 7a204e9f6c67
Revises: 3ed7dd81fb12
Create Date: 2022-04-16 01:27:02.742367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a204e9f6c67'
down_revision = '3ed7dd81fb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealers')
    op.drop_table('deals')
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cars_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cars_pkey'),
    sa.UniqueConstraint('brand', name='cars_brand_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('deals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name='deals_car_id_fkey'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name='deals_dealer_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='deals_pkey')
    )
    op.create_table('dealers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cars_sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('earnings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dealers_pkey'),
    sa.UniqueConstraint('name', name='dealers_name_key')
    )
    # ### end Alembic commands ###
