"""empty message

Revision ID: b153c90e59cf
Revises: 3018bd94b3cc
Create Date: 2022-04-15 22:17:48.471733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b153c90e59cf'
down_revision = '3018bd94b3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deals_dealer_id_fkey', 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'dealers', ['dealer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key('deals_dealer_id_fkey', 'deals', 'dealers', ['dealer_id'], ['id'])
    # ### end Alembic commands ###
